
name: loan_default_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pandas=2.1.3
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - hydra-core=1.3.2
  - pyyaml=6.0.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - xgboost==2.0.2
      - optuna==3.4.0
      - shap==0.43.0