name: model_monitoring
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pandas=2.1.3
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - scipy=1.11.3
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - xgboost==2.0.2
      - plotly==5.18.0
      - dash==2.14.1
      - dash-bootstrap-components==1.5.0